[project]
authors = ["Marios Karampasis <marios.karampasis@uu.nl>"]
channels = ["conda-forge"]
description = "Initially created by JoerivanEngelen <joeri.vanengelen@deltares.nl, so that I can run imod_coupler. I then added more libs to be able to run WS_Mdl functions."
name = "pixi"
platforms = ["win-64"]
version = "0.2.0"

[tasks]
install = "pip install git+https://github.com/Deltares/imod_coupler.git@f262843#subdirectory=pre-processing"


[dependencies]
xugrid = "*"
filelock = "*"
geopandas = "*"
rioxarray = "*"
bottleneck = "*"
jupyter = "*"
pandamesh = "*"
pip = "*"
pytest = "*"
itables = ">=2.5.2,<3"

[pypi-dependencies]
imod = { git = "https://github.com/Deltares/imod-python.git", rev = "28de6f78680c730a23a67474396f9466b18dcd12"}
WS_Mdl = { path = 'G:/', editable = true }
sfrmaker = "==0.12.1"
