[workspace]
authors = ["Marios Karampasis <marios.karampasis@uu.nl>"]
channels = ["conda-forge", "bioconda"]
description = "Initially created by JoerivanEngelen <joeri.vanengelen@deltares.nl, so that I can run imod_coupler. I then added more libs to be able to run WS_Mdl functions."
name = "pixi"
platforms = ["win-64"]
version = "0.2.0"

[tasks]
install = "pip install git+https://github.com/Deltares/imod_coupler.git@f262843#subdirectory=pre-processing"


[dependencies]
python = "3.13.*"
xugrid = "*"
filelock = "*"
geopandas = "*"
rioxarray = "*"
bottleneck = "*"
jupyter = "*"
pandamesh = "*"
pip = "*"
pytest = "*"
itables = ">=2.5.2,<3"
plotly = "*"
graphviz = ">=14.0.5,<15"
ibridges = ">=2.0.1,<3"
sfrmaker = "*"

[pypi-dependencies]
snakemake = "*"
imod = { git = "https://github.com/Deltares/imod-python.git", rev = "1.0.0rc7"}
WS_Mdl = { path = './', editable = true }